name: build

on:
  push:
    branches:
      - main
      - dev*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '3.1', '3.2', '3.3', '3.4' ]
    steps:
      - uses: actions/checkout@v4
      - name: Install libpng and libjpeg
        run: sudo apt-get install -y libpng-dev libjpeg-dev
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test with Rake
        run: bundle exec rake
